Models/CountryMaster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DropDownExaple.Models
{
    public partial class CountryMaster
    {
        [Key]
        public int ID { get; set; }

        [Display(Name="Country Name")]
        public string Name { get; set; }
        
        public string CountryCode { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace DropDownExaple.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DropDownExaple.Data;
using DropDownExaple.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;

namespace DropDownExaple.Controllers
{
    public class DemoController : Controller
    {
        private readonly AllSampleCodeContext _context;

        public DemoController(AllSampleCodeContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<CountryMaster> countryList = new List<CountryMaster>();

            // -- Gettin data from Database Using EntityFrameworkCore ---
            countryList = (from product in _context.CountryMaster
                           select product).ToList();

            // -- Inserting Select Item in List -------
            countryList.Insert(0, new CountryMaster { ID = 0, Name = "Select" });

            //-- Assigning country list to ViewBag.ListofCountry --------
            ViewBag.ListOfCountry = countryList;
            return View();
        }

        [HttpPost]
        public IActionResult Index(CountryMaster CountryMaster)
        {
            //-- validation -------//
            if(CountryMaster.ID == 0 )
            {
                ModelState.AddModelError("","Select Country");
            }


            //---- Getting Selected Value
            int SelectedValue = CountryMaster.ID;
            ViewBag.SelectedValue = CountryMaster.ID;

            //--- Setting Data back to ViewBag after Posting Form ---

            List<CountryMaster>countryList = new List<Models.CountryMaster>();

            countryList = (from product in _context.CountryMaster 
                            select product).ToList();

            countryList.Insert(0, new CountryMaster {ID = 0, Name = "Select"});
            ViewBag.ListofCountry = countryList;

            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DropDownExaple.Models;

namespace DropDownExaple.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Demo/Index.cshtml
@model DropDownExaple.Models.CountryMaster
@{
    <form asp-controller="Demo" asp-action="Index" method="post" class="form-horizontal" role="form">  
        <div class="form-group">  
            <div class="alert-danger" asp-validation-summary="ModelOnly"></div> 
            <div class="row">                   
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">  
                    <label asp-for="Name" class="control-label"></label>  
                    <select asp-for="ID" class="form-control"   
                      asp-items="@(new SelectList(@ViewBag.ListofCountry,"ID", "Name"))">  
                    </select>  
                </div>  
            </div>  
        </div>  
        <div class="form-group">  
            <div class="row">  
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">  
                    <input id="Submit1" type="submit" value="submit" />  
                </div>  
            </div>  
        </div>  
        <div class="form-group">  
            <div class="row">  
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">  
                    @if (ViewBag.SelectedValue != null)  
                    {  
                        <text>Selected Country ID: </text> @ViewBag.SelectedValue;  
                    }  
                </div>  
            </div>  
        </div>  
    </form> 
}  

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DropDownExaple</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DropDownExaple</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DropDownExaple - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>